package RadeCom::Model::User;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'RadeCom::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

RadeCom::Model::User - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<RadeCom>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<RadeCom::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

radeonares

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
